import os

SECRET_KEY = os.environ["SECRET_KEY"]

DATABASE_USER = os.environ["DATABASE_USER"]
DATABASE_PASSWORD = os.environ["DATABASE_PASSWORD"]
DATABASE_HOST = os.environ["DATABASE_HOST"]
DATABASE_PORT = os.environ["DATABASE_PORT"]
DATABASE_NAME = os.environ["DATABASE_NAME"]

DATABASE_URI = (f"postgres://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}"
                f"/{DATABASE_NAME}")

MOVIE_DATABASE_API_KEY = os.environ["MOVIE_DATABASE_API_KEY"]
MOVIE_DATABASE_BASE_URL = os.environ["MOVIE_DATABASE_BASE_URL"]

PRODUCTION_URL = os.environ.get("PRODUCTION_URL", "")
